from typing import List, Dict, Any
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.models.models import Case, Finding, Event, AuditLog, Artifact, Evidence
from app.schemas.schemas import FindingResponse, FindingCreate, FindingUpdate
from app.ai.anomaly_engine import AnomalyDetectionEngine

router = APIRouter(tags=["Findings & Examiner Validation Gate (Module 5 & 6)"])


@router.get("/cases/{case_id}/findings", response_model=List[FindingResponse])
def list_findings(case_id: str, db: Session = Depends(get_db)):
    """Lists all investigative findings with validation status and supporting event link."""
    findings = db.query(Finding).filter(Finding.case_id == case_id).order_by(Finding.confidence_score.desc()).all()
    results = []
    for f in findings:
        resp = FindingResponse.model_validate(f)
        if f.event:
            resp.linked_event = f.event
        results.append(resp)
    return results


@router.patch("/findings/{finding_id}/validate", response_model=FindingResponse)
def validate_finding(finding_id: str, payload: FindingUpdate, db: Session = Depends(get_db)):
    """
    Examiner Validation Gate:
    Enforces mandatory human-in-the-loop review. The lead forensic examiner accepts,
    rejects, or modifies AI-correlated findings before they are included in court-ready reports.
    """
    finding = db.query(Finding).filter(Finding.finding_id == finding_id).first()
    if not finding:
        raise HTTPException(status_code=404, detail="Finding not found")

    old_status = finding.validation_status
    finding.validation_status = payload.validation_status

    if payload.investigator_notes:
        finding.investigator_notes = payload.investigator_notes
    if payload.finding_title:
        finding.finding_title = payload.finding_title
    if payload.description:
        finding.description = payload.description

    # Log to audit trail
    db.add(AuditLog(
        case_id=finding.case_id,
        user_name="Forensic Examiner (Validation Gate)",
        action="FINDING_VALIDATION_UPDATED",
        details=(
            f"Finding '{finding.finding_title}' updated from {old_status} -> {payload.validation_status}. "
            f"Notes: {payload.investigator_notes or 'None'}"
        )
    ))
    db.commit()
    db.refresh(finding)

    resp = FindingResponse.model_validate(finding)
    if finding.event:
        resp.linked_event = finding.event
    return resp


@router.post("/cases/{case_id}/correlate", response_model=Dict[str, Any])
def run_correlation_and_detection(case_id: str, db: Session = Depends(get_db)):
    """
    Executes behavioral anomaly correlation across all normalized events in the case.
    Detects abnormal execution, persistence, C2 beacons, and proposes AI findings for validation.
    """
    case = db.query(Case).filter(Case.case_id == case_id).first()
    if not case:
        raise HTTPException(status_code=404, detail="Case not found")

    events = (
        db.query(Event)
        .join(Artifact, Event.artifact_id == Artifact.artifact_id)
        .join(Evidence, Artifact.evidence_id == Evidence.evidence_id)
        .filter(Evidence.case_id == case_id)
        .all()
    )

    new_findings_count = 0
    anomalies_updated = 0

    for ev in events:
        is_anom, score, title, ftype = AnomalyDetectionEngine.evaluate_event(ev.event_type, ev.details or {})
        if is_anom:
            ev.is_anomalous = 1
            ev.anomaly_score = score
            anomalies_updated += 1

            # Propose finding if none already exists for this event
            existing_f = db.query(Finding).filter(Finding.case_id == case_id, Finding.event_id == ev.event_id).first()
            if not existing_f and title and ftype:
                new_finding = Finding(
                    case_id=case_id,
                    event_id=ev.event_id,
                    finding_title=title,
                    finding_type=ftype,
                    description=f"Behavioral anomaly identified in {ev.source_entity}: {str(ev.details)[:200]}",
                    confidence_score=score,
                    validation_status="Pending",
                    investigator_notes="Generated by Anomaly Engine; awaiting examiner review."
                )
                db.add(new_finding)
                new_findings_count += 1

    db.commit()

    return {
        "status": "Correlation complete",
        "events_scanned": len(events),
        "anomalous_events_flagged": anomalies_updated,
        "new_findings_proposed": new_findings_count
    }
